# Generated by Django 3.2.14 on 2022-07-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='procedure',
            field=models.ManyToManyField(blank=True, null=True, related_name='receptions', to='receptions.Procedure'),
        ),
    ]
