# Generated by Django 3.2.14 on 2022-11-01 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reception',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='receptions.patient', verbose_name='Пациент'),
        ),
        migrations.AddField(
            model_name='reception',
            name='procedure',
            field=models.ManyToManyField(blank=True, related_name='receptions', to='receptions.ProcedurePart', verbose_name='Процедуры'),
        ),
        migrations.AddField(
            model_name='procedurepart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proc_parts', to='receptions.part'),
        ),
        migrations.AddField(
            model_name='procedurepart',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proc_parts', to='receptions.procedure'),
        ),
        migrations.AddField(
            model_name='diagnosispart',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diag_parts', to='receptions.diagnosis'),
        ),
        migrations.AddField(
            model_name='diagnosispart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diag_parts', to='receptions.part'),
        ),
    ]
