# Generated by Django 3.2.14 on 2022-07-30 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receptions', '0003_alter_reception_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
