# Generated by Django 3.2.14 on 2022-07-30 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receptions', '0004_alter_reception_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='doctor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='auth.user'),
            preserve_default=False,
        ),
    ]
